name: Release Latest Changelog

on:
  push:
    tags:
      - 'v*'

jobs:

  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      
      - name: Peek next version number
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          dry_run: true

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.3.1
        with:
          myToken: ${{ secrets.GH_TOKEN }}
      
      - name: Publish latest release details to Discord Webhook
        run: |
          : # Retrieve details about most current change
          head_commit_ts=$(git log -1 --format=%cd)
          tag="${{ steps.tag_version.outputs.previous_tag }}"

          : # Process changelog between current tag and the previous one 
          changelog="${{ steps.changelog.outputs.changelog }}"

          timestamp='`'"$head_commit_ts"'`'
          head_commit_msg="$(git log -1 --pretty=format:"%s")"
          current_tag='`'"$tag"'`'

          JSON_STRING=$( jq -n \
                  --arg ct "AzteMarket $current_tag was released!" \
                  --arg cm "$head_commit_msg" \
                  --arg ts "$timestamp" \
                  --arg changelog "$changelog" \
                  '{
                        "content": "",
                        "embeds": [
                            {
                            "title": $ct,
                            "description": $cm,
                            "color": 2123412,
                            "fields": [
                                {
                                    "name": "Changes",
                                    "value": $changelog
                                },
                                {
                                    "name": "Timestamp",
                                    "value": $ts
                                }
                            ]
                            }
                        ]
                    }' 
            )

          curl -H "Content-Type: application/json" -d "$JSON_STRING" ${{ secrets.DISCORD_WEBHOOK_CHANGELOG }}